version: 2.1
jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  
  # Puppeteer Example
  test-puppeteer:
    working_directory: ~/app
    docker:
      - image: saucelabs/stt-puppeteer-jest-node:latest
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Puppeteer Tests
          command: |
            saucectl run -c ./.sauce/puppeteer.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Playwright Example
  test-playwright:
    working_directory: ~/app
    docker:
      - image: saucelabs/stt-playwright-jest-node:latest
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Playwright Tests
          command: |
            saucectl run -c ./.sauce/playwright.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Testcafe Example
  test-testcafe:
    working_directory: ~/app
    docker:
      - image: saucelabs/stt-testcafe-node:latest
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Testcafe Tests
          command: |
            saucectl run -c ./.sauce/testcafe.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Cypress Example
  test-cypress:
    working_directory: ~/app
    docker:
      - image: saucelabs/stt-cypress-mocha-node:latest
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Testcafe Tests
          command: |
            saucectl run -c ./.sauce/cypress.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - test-puppeteer:
          requires:
            - setup
      - test-playwright:
          requires:
            - setup
      - test-testcafe:
          requires:
            - setup
