version: 2.1
jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run:
          name: Download saucectl
          command: |
              SAUCECTL_VERSION=0.23.2
              SAUCECTL_BINARY=saucectl_${SAUCECTL_VERSION}_linux_64-bit.tar.gz
              curl -L -o ${SAUCECTL_BINARY} \
                -H "Accept: application/octet-stream" \
                https://github.com/saucelabs/saucectl/releases/download/v${SAUCECTL_VERSION}/${SAUCECTL_BINARY} \
                && tar -xvzf ${SAUCECTL_BINARY}
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  # Cypress Example
  test-cypress:
    working_directory: ~/app
    docker:
      - image: ubuntu:20.04
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Cypress Tests
          command: |
            chmod -R 777 ./tests
            sed -i 's/fileTransfer: mount/fileTransfer: copy/g' ./.sauce/cypress.yml
            ./saucectl run -c ./.sauce/cypress.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Playwright Example
  test-playwright:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Playwright Tests
          command: |
            chmod -R 777 ./tests
            ./saucectl run -c ./.sauce/playwright.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Puppeteer Example
  test-puppeteer:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Puppeteer Tests
          command: |
            chmod -R 777 ./tests
            ./saucectl run -c ./.sauce/puppeteer.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

  # Testcafe Example
  test-testcafe:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Testcafe Tests
          command: |
            chmod -R 777 ./tests
            ./saucectl run -c ./.sauce/testcafe.yml
          environment:
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

workflows:
  version: 2
  default_workflow:
    jobs:
      - setup
      - test-cypress:
          requires:
            - setup
      - test-playwright:
          requires:
            - setup
      - test-puppeteer:
          requires:
            - setup
      - test-testcafe:
          requires:
            - setup