# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sauce Pipeline Browser Tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}

jobs:
  puppeteer:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/sauce-puppeteer:3.0.4-saucectl0.4.2
     
    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/puppeteer.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
  playwright:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/sauce-playwright:1.0.0-saucectl0.4.2

    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home
      
      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/playwright.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions

  testcafe:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/sauce-testcafe:1.8.5-saucectl0.6.3

    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home
      
      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/testcafe.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
